<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Company.Identity.Authorization.AspNetCore</RootNamespace><AssemblyName>Company.Identity.Authorization.AspNetCore</AssemblyName><PackageId>Company.Identity.Authorization.AspNetCore</PackageId></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup><ItemGroup><ProjectReference Include="../Company.Identity.Authorization/Company.Identity.Authorization.csproj" /></ItemGroup></Project>
