<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Identity.Persistence.KeyManagement</RootNamespace>
    <AssemblyName>Identity.Persistence.KeyManagement</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Identity.Domain/Identity.Domain.csproj" />
    <ProjectReference Include="../Identity.Application/Identity.Application.csproj" />
    <ProjectReference Include="../Identity.Contracts/Identity.Contracts.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Oracle.EntityFrameworkCore" />
  </ItemGroup>
</Project>
