<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Identity.Infrastructure</RootNamespace><AssemblyName>Identity.Infrastructure</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../Identity.Application/Identity.Application.csproj" /><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
