<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Company.Identity.Authentication.AspNetCore</RootNamespace><AssemblyName>Company.Identity.Authentication.AspNetCore</AssemblyName><PackageId>Company.Identity.Authentication.AspNetCore</PackageId></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup><ItemGroup><ProjectReference Include="../Company.Identity.Authentication/Company.Identity.Authentication.csproj" /><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" /></ItemGroup></Project>
