<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Identity.Persistence.EntityFrameworkCore</RootNamespace><AssemblyName>Identity.Persistence.EntityFrameworkCore</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../Identity.Domain/Identity.Domain.csproj" /><ProjectReference Include="../Identity.Application/Identity.Application.csproj" /><PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" /><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" /><PackageReference Include="Oracle.EntityFrameworkCore" /><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" /></ItemGroup></Project>
