<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Company.Identity.PermissionDiscovery</RootNamespace><AssemblyName>Company.Identity.PermissionDiscovery</AssemblyName><PackageId>Company.Identity.PermissionDiscovery</PackageId></PropertyGroup><ItemGroup><ProjectReference Include="../Company.Identity.Abstractions/Company.Identity.Abstractions.csproj" /></ItemGroup></Project>
