<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Company.Identity.PermissionRegistration</RootNamespace><AssemblyName>Company.Identity.PermissionRegistration</AssemblyName><PackageId>Company.Identity.PermissionRegistration</PackageId></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Company.Identity.Abstractions/Company.Identity.Abstractions.csproj" /></ItemGroup>
</Project>
